version: '3.11'

services:

  ods:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
    ports:
      - 5001:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
    env_file:
      - ".env"
    command: gunicorn ods:app --workers 3 --bind :5000 --timeout 900
